// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821215107_expandanimaltypes")]
    partial class expandanimaltypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Bio");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<int>("Weight");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");
                });

            modelBuilder.Entity("AnimalShelter.Models.Bird", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("BirdBreed");

                    b.HasDiscriminator().HasValue("Bird");

                    b.HasData(
                        new
                        {
                            AnimalId = 11,
                            Age = 3,
                            Bio = "Very communicative!",
                            Gender = "Male",
                            Name = "Chirpy",
                            Weight = 1,
                            BirdBreed = "Parakeet"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 12,
                            Bio = "Escape artist!",
                            Gender = "Female",
                            Name = "Stripes",
                            Weight = 1,
                            BirdBreed = "Zebra Finch"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 9,
                            Bio = "Not friendly!",
                            Gender = "Male",
                            Name = "Blue",
                            Weight = 3,
                            BirdBreed = "Macaw"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 5,
                            Bio = "Regal!",
                            Gender = "Female",
                            Name = "Sam",
                            Weight = 12,
                            BirdBreed = "Bald Eagle"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 14,
                            Bio = "Extremely fast!",
                            Gender = "Female",
                            Name = "Ozzie",
                            Weight = 45,
                            BirdBreed = "Emu"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Canine", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("CanineBreed");

                    b.HasDiscriminator().HasValue("Canine");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Bio = "Loves fetch!",
                            Gender = "Female",
                            Name = "Rex",
                            Weight = 42,
                            CanineBreed = "Labrador Retreiver"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Bio = "Needs leash traning!",
                            Gender = "Female",
                            Name = "Ramona",
                            Weight = 55,
                            CanineBreed = "German Shepard"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 6,
                            Bio = "Yappy!",
                            Gender = "Male",
                            Name = "Ren",
                            Weight = 12,
                            CanineBreed = "Chihuahua"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 3,
                            Bio = "Very loyal!",
                            Gender = "Male",
                            Name = "Lassie",
                            Weight = 47,
                            CanineBreed = "Border Collie"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            Bio = "Courageous!",
                            Gender = "Female",
                            Name = "Spot",
                            Weight = 41,
                            CanineBreed = "Dalmation"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Equine", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("EquineBreed");

                    b.HasDiscriminator().HasValue("Equine");

                    b.HasData(
                        new
                        {
                            AnimalId = 26,
                            Age = 6,
                            Bio = "Adventurous!",
                            Gender = "Male",
                            Name = "Artax",
                            Weight = 1256,
                            EquineBreed = "Arabian"
                        },
                        new
                        {
                            AnimalId = 27,
                            Age = 12,
                            Bio = "Very fast!",
                            Gender = "Male",
                            Name = "Secretariat",
                            Weight = 986,
                            EquineBreed = "Thoroughbred"
                        },
                        new
                        {
                            AnimalId = 28,
                            Age = 5,
                            Bio = "Kind hearted!",
                            Gender = "Male",
                            Name = "Black Beauty",
                            Weight = 1124,
                            EquineBreed = "American Quarter"
                        },
                        new
                        {
                            AnimalId = 29,
                            Age = 7,
                            Bio = "Can do math!",
                            Gender = "Female",
                            Name = "Einstein",
                            Weight = 564,
                            EquineBreed = "Miniature"
                        },
                        new
                        {
                            AnimalId = 30,
                            Age = 9,
                            Bio = "A former movie star!",
                            Gender = "Male",
                            Name = "Cojo Rojo",
                            Weight = 1347,
                            EquineBreed = "Appaloosa"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Feline", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("FelineBreed");

                    b.HasDiscriminator().HasValue("Feline");

                    b.HasData(
                        new
                        {
                            AnimalId = 6,
                            Age = 3,
                            Bio = "Loves belly rubs!",
                            Gender = "Male",
                            Name = "Whiskers",
                            Weight = 10,
                            FelineBreed = "Tabby"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 6,
                            Bio = "Ornery!",
                            Gender = "Male",
                            Name = "Simba",
                            Weight = 12,
                            FelineBreed = "Maine Coon"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 9,
                            Bio = "Loves chasing toys!",
                            Gender = "Female",
                            Name = "Snowball",
                            Weight = 2,
                            FelineBreed = "Persian"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 4,
                            Bio = "Dumb but loveable!",
                            Gender = "Male",
                            Name = "Stimpy",
                            Weight = 15,
                            FelineBreed = "Manx"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 8,
                            Bio = "Hypo-allergenic!",
                            Gender = "Female",
                            Name = "Fluffy",
                            Weight = 9,
                            FelineBreed = "Sphynx"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Reptile", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("ReptileBreed");

                    b.HasDiscriminator().HasValue("Reptile");

                    b.HasData(
                        new
                        {
                            AnimalId = 16,
                            Age = 4,
                            Bio = "Will bite!",
                            Gender = "Female",
                            Name = "Chompy",
                            Weight = 1,
                            ReptileBreed = "Snapping Turtle"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 13,
                            Bio = "Gives great hugs!",
                            Gender = "Female",
                            Name = "Kaa",
                            Weight = 47,
                            ReptileBreed = "Boa Constrictor"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 5,
                            Bio = "Loves lounging in the sun!",
                            Gender = "Male",
                            Name = "Puff",
                            Weight = 24,
                            ReptileBreed = "Kimodo Dragon"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 8,
                            Bio = "Loves to wrestle!",
                            Gender = "Female",
                            Name = "Alli",
                            Weight = 46,
                            ReptileBreed = "Alligator"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 2,
                            Bio = "Has a British Accent!",
                            Gender = "Male",
                            Name = "Geico",
                            Weight = 1,
                            ReptileBreed = "Gecko"
                        },
                        new
                        {
                            AnimalId = 21,
                            Age = 2,
                            Bio = "Loves cheese!",
                            Gender = "Male",
                            Name = "Templeton",
                            Weight = 1
                        },
                        new
                        {
                            AnimalId = 22,
                            Age = 1,
                            Bio = "Goes west!",
                            Gender = "Male",
                            Name = "Fievel",
                            Weight = 1
                        },
                        new
                        {
                            AnimalId = 23,
                            Age = 3,
                            Bio = "Loves a good maze!",
                            Gender = "Female",
                            Name = "Creampuff",
                            Weight = 2
                        },
                        new
                        {
                            AnimalId = 24,
                            Age = 4,
                            Bio = "Cuddly!",
                            Gender = "Female",
                            Name = "Cookie",
                            Weight = 3
                        },
                        new
                        {
                            AnimalId = 25,
                            Age = 2,
                            Bio = "Loves to play hide and seek!",
                            Gender = "Male",
                            Name = "Slinky",
                            Weight = 3
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Rodent", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("RodentBreed");

                    b.HasDiscriminator().HasValue("Rodent");
                });
#pragma warning restore 612, 618
        }
    }
}
