// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821181005_breed")]
    partial class breed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Bio");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<int>("Weight");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");
                });

            modelBuilder.Entity("AnimalShelter.Models.Canine", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("CanineBreed");

                    b.HasDiscriminator().HasValue("Canine");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Bio = "Loves fetch!",
                            Gender = "Female",
                            Name = "Rex",
                            Weight = 42,
                            CanineBreed = "Labrador Retreiver"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Feline", b =>
                {
                    b.HasBaseType("AnimalShelter.Models.Animal");

                    b.Property<string>("FelineBreed");

                    b.HasDiscriminator().HasValue("Feline");

                    b.HasData(
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Bio = "Loves belly rubs!",
                            Gender = "Male",
                            Name = "Whiskers",
                            Weight = 10,
                            FelineBreed = "Tabby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
